---
title: "KNN method"
output: pdf_document
---

```{r}
path <- "/Users/liushuhao/Desktop/SOA Case Competitoin/R_Project/players_joined_subset.rda"
load(path)
```

```{r}
#the normalization function is created
norm <-function(x) { 
  upper = quantile(x, .98)
  lower = quantile(x, .02)
  x_norm <- (x-lower)/(upper-lower)
  x_norm[which(x_norm > 1)] = 1
  x_norm[which(x_norm < 0)] = 0
  x_norm
}
```

```{r}
set.seed(123)
#Generate a random number that is 90% of the total number of rows in dataset.
ran <- sample(1:nrow(Tourn.JoinedTable.ranked), 0.9 * nrow(Tourn.JoinedTable.ranked))

playerIndex <- which(colnames(Tourn.JoinedTable.ranked) == "Player")
rankIndex <- which(colnames(Tourn.JoinedTable.ranked) == "nation rank")
yearIndex <- which(colnames(Tourn.JoinedTable.ranked) == "Year")
Tourn_norm <- as.data.frame(lapply(Tourn.JoinedTable.ranked[,-c(playerIndex,rankIndex,yearIndex)], norm))

Tourn_train <- Tourn_norm[ran,] 
Tourn_test <- Tourn_norm[-ran,] 

Tourn_target_category <- as.data.frame(Tourn.JoinedTable.ranked)[ran,rankIndex]
Tourn_test_category <- as.data.frame(Tourn.JoinedTable.ranked)[-ran,rankIndex]

library(class)
#run knn function
k <- 14
error <- 9
pr <- knn(Tourn_train,Tourn_test,cl=Tourn_target_category,k=k,use.all = TRUE)
accuracy <- sum(abs(as.numeric(pr) - as.numeric(Tourn_test_category)) <= error) / length(pr)
accuracy
```

```{r}
LeagePlayerIndex <- which(colnames(League.JoinedTable) == "Player")
League_norm <- as.data.frame(lapply(League.JoinedTable[,-LeagePlayerIndex], norm))
Target_category <- as.data.frame(Tourn.JoinedTable.ranked)[,rankIndex]
predRank <- knn(Tourn_norm,League_norm,cl=Target_category,k=k)
#League.JoinedTable$"Pred Rank" <- predRank
table(predRank)
```

Normalize data
```{r}
League.JoinedTable.norm <- League.JoinedTable

for(att in names(League.JoinedTable.norm)) {
  if(att != "Player" && att != "Pred Rank") {
    League.JoinedTable.norm[, att] <- norm(unlist(League.JoinedTable.norm[, att]))
  }
}
League.JoinedTable.norm$"Pred Rank" <- predRank
PlayerNation <- sapply(League.JoinedTable.norm$Player, function(x) {LeagueShoot$Nation[unlist(which(LeagueShoot$Player == x))[1]]})
League.JoinedTable.norm$"Nation" <- PlayerNation

```

```{r}
save(League.JoinedTable.norm, file = "League_final_norm.rda")
```

```{r}
library("xlsx")
write.xlsx(League.JoinedTable.norm, file="leage player ranking.xlsx", sheetName = "League player", append = FALSE)
```