---
title: "model fitting"
author: "Shuhao Liu"
date: "19/02/2022"
output: html_document
---

```{r}
load("/Users/liushuhao/Desktop/SOA Case Competitoin/R_Project/players_joined_subset.rda")
```

```{r}
#standardize attributes
League.JoinedTable.Tailored.standardized <- as.data.frame(cbind(League.JoinedTable.Tailored[,1], scale(League.JoinedTable.Tailored[,2:ncol(League.JoinedTable.Tailored)])))
Tourn.JoinedTable.Tailored.standardized <- as.data.frame(cbind(Tourn.JoinedTable.Tailored[,1], scale(Tourn.JoinedTable.Tailored[,2:ncol(Tourn.JoinedTable.Tailored)])))
```

# Select defenders

```{r}
defense_score0 <- function(player) {
   1.1 * player$"90s" +
   0.9 * player$"Tackles Tkl/min" + 
   0.7 * player$"TklW%" * (player$"Tackles Tkl/min" > -0.85) +  # -0.85 is the lower bound of 60% CI
   -0.9 * player$"Vs Dribbles Past/min" + 
   0.05 * player$"Pressures Succ %" + 
   1.5 * player$"Pressures %" + 
   1.5 * player$"Blocks Blocks/min" + 
   0.9 * player$"Int/min"+ 
   0.5 * player$"Clr/min" + 
   -1.5 * player$"Err/min"
}
```

```{r fig.height=8, fig.width=14}
# Note: player is the standardized data
defense_score <- function(player, coeffs) {
   coeffs[1] * player$"90s" +
   coeffs[2] * player$"Tackles Tkl/min" + 
   coeffs[3] * player$"TklW%" * (player$"Tackles Tkl/min" > -0.85) +  # -0.85 is the lower bound of 60% CI
   coeffs[4] * player$"Vs Dribbles Past/min" + 
   coeffs[5] * player$"Pressures Succ %" + 
   coeffs[6] * player$"Pressures %" + 
   coeffs[7] * player$"Blocks Blocks/min" + 
   coeffs[8] * player$"Int/min"+ 
   coeffs[9] * player$"Clr/min" + 
   coeffs[10] * player$"Err/min"
}

```

```{r}
coef3 <- c(1.05,  0.8,  0.65, -0.70,  0.03,  1.45,  1.45 , 0.85,  0.40, -1.50)
LeagueDefense.score <- defense_score(League.JoinedTable.Tailored.standardized, coef3)
TournDefense.score <- cbind(Tourn.JoinedTable.Tailored[,1], "Score" = defense_score(Tourn.JoinedTable.Tailored.standardized, coef3))
LeagueDefense.rank <- rank(LeagueDefense.score)
TournDefense.rank <- rank(TournDefense.rank)

#par(mfrow = c(1, 2))
plot(LeagueDefense.score, ylab = "score")
#plot(TournDefense.score, ylim = c(-30, 42))
threshold <- 30
accuracy <- sum(abs(LeagueDefense.rank - TournDefense.rank) <= threshold)/length(LeagueDefense.rank)
accuracy
```

```{r}
ds <- function(coeffs) {
   score <- function(player) {
      coeffs[1] * player$"90s" +
      coeffs[2] * player$"Tackles Tkl/min" + 
      coeffs[3] * player$"TklW%" * (player$"Tackles Tkl/min" > -0.85) +  # -0.85 is the lower bound of 60% CI
      coeffs[4] * player$"Vs Dribbles Past/min" + 
      coeffs[5] * player$"Pressures Succ %" + 
      coeffs[6] * player$"Pressures %" + 
      coeffs[7] * player$"Blocks Blocks/min" + 
      coeffs[8] * player$"Int/min"+ 
      coeffs[9] * player$"Clr/min" + 
      coeffs[10] * player$"Err/min"
   }
   
   LeagueDefense.rank <- rank(score(League.JoinedTable.Tailored.standardized))
   TournDefense.rank <- rank(score(Tourn.JoinedTable.Tailored.standardized))
   
   threshold <- 30
   accuracy <- sum(abs(LeagueDefense.rank - TournDefense.rank) <= threshold)/length(LeagueDefense.rank)
   accuracy
}

coef1 <- c(1.0,  0.9,  0.5,  1.1, -0.5,  0.7,  0.9,  0.5,  1.3, -1.3)
coef2 <- c(1.10,  0.90,  0.70, -0.90,  0.05,  1.50,  1.50 , 0.90,  0.50, -1.50)
coef3 <- c(1.05,  0.8,  0.65, -0.70,  0.03,  1.45,  1.45 , 0.85,  0.40, -1.50)
ds(coef1)
ds(coef2)
ds(coef3)
# 6 iterations: 1.05  0.80  0.65 -0.70  0.03  1.45  1.45  0.85  0.40 -1.50
```

```{r}

score <- function(coeffs, player) {
   coeffs[1] * player$"90s" +
   coeffs[2] * player$"Tackles Tkl/min" + 
   coeffs[3] * player$"TklW%" * (player$"Tackles Tkl/min" > -0.85) +  # -0.85 is the lower bound of 60% CI
   coeffs[4] * player$"Vs Dribbles Past/min" + 
   coeffs[5] * player$"Pressures Succ %" + 
   coeffs[6] * player$"Pressures %" + 
   coeffs[7] * player$"Blocks Blocks/min" + 
   coeffs[8] * player$"Int/min"+ 
   coeffs[9] * player$"Clr/min" + 
   coeffs[10] * player$"Err/min"
}

accuracy <- 0
coef
threshold <- 5
u = 1.5
l = -1.5
g = 0.05

for(c1 in seq(1.10-0.2,1.10+0.2, g)){
   for(c2 in seq(0.90-0.2,0.90+0.2, g)){
   for(c3 in seq(0.70-0.2,0.70+0.2, g)){
   for(c4 in seq(-0.90-0.2, -0.90+0.2, g)){
      
   for(c5 in seq(0.03,0.07, 0.02)){
   for(c6 in seq(1.45,2, 0.1)){
   for(c7 in seq(1.45,2, 0.1)){
   for(c8 in seq(0.90-0.2,0.90+0.2, g)){
   for(c9 in seq(0.1,0.6, 0.1)){
   for(c10 in seq(-1.8, -1.2, 0.1)){
      LeagueDefense.rank <- rank(score(c(c1,c2,c3,c4,c5,c6,c7,c8,c9,c10), League.JoinedTable.Tailored.standardized))
      TournDefense.rank <- rank(score(c(c1,c2,c3,c4,c5,c6,c7,c8,c9,c10),Tourn.JoinedTable.Tailored.standardized))
      acc <- sum(abs(LeagueDefense.rank - TournDefense.rank) <=  threshold)/length(LeagueDefense.rank)
      if(acc > accuracy) {
         accuracy <- acc
         coef <- c(c1,c2,c3,c4,c5,c6,c7,c8,c9,c10)
      }
}
}
}
}
}
}
}
}
   }
   print("finish 1 iteration")
}

print(accuracy)
print(coef)
```
